baseurl = "https://nicolasmassicard.github.io/"
languageCode = "fr-fr"
title = "C'est une demo!"
theme="landing-page-hugo"
[params]
  description = "le meilleur site du monde"
  
[[params.social]]
	title = "Couriel"
	icom = "envelope-o"
	url = "mailto:nicolas.massicard@gmail.com"
[[params.social]]
	title = "twitter"
	icon = "twitter"
	url = "https://twitter.com/GauloisNB"

